-- leader
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.keymap.set("n", " ", "<Nop>")

-- lsp commands
-- vim.api.nvim_create_autocmd('LspAttach', {
--   desc = 'LSP actions',
--   callback = function()
--     -- local setkey = function(mode, lhs, rhs, desc)
--     --   local opts = {buffer = true, desc = desc}
--     --   vim.keymap.set(mode, lhs, rhs, opts)
--     -- end
--
--     local setkey = vim.keymap.set;
--
--     -- Displays hover information about the symbol under the cursor
--     setkey('n', 'K', '<cmd>lua vim.lsp.buf.hover()<cr>')
--
--     -- Jump to the definition
--     setkey('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<cr>')
--
--     -- Jump to declaration
--     setkey('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<cr>')
--
--     -- Lists all the implementations for the symbol under the cursor
--     setkey('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<cr>')
--
--     -- Jumps to the definition of the type symbol
--     setkey('n', 'go', '<cmd>lua vim.lsp.buf.type_definition()<cr>')
--
--     -- Lists all the references 
--     setkey('n', 'gr', '<cmd>lua vim.lsp.buf.references()<cr>')
--
--     -- Displays a function's signature information
--     setkey('n', 'gs', '<cmd>lua vim.lsp.buf.signature_help()<cr>')
--
--     -- Renames all references to the symbol under the cursor
--     setkey('n', '<F2>', '<cmd>lua vim.lsp.buf.rename()<cr>')
--
--     -- Selects a code action available at the current cursor position
--     setkey('n', '<F4>', '<cmd>lua vim.lsp.buf.code_action()<cr>')
--
--     -- Show diagnostics in a floating window
--     setkey('n', 'gl', '<cmd>lua vim.diagnostic.open_float()<cr>')
--
--     -- Move to the previous diagnostic
--     setkey('n', '[d', '<cmd>lua vim.diagnostic.goto_prev()<cr>')
--
--     -- Move to the next diagnostic
--     setkey('n', ']d', '<cmd>lua vim.diagnostic.goto_next()<cr>')
--   end
-- })
